# 站点设置
title: 石大时光圈项目文档
description: 石河子大学校园APP开源项目文档与开发指南
url: "https://asherde.github.io/StoneU_Hood_docs"
baseurl: "/StoneU_Hood_docs"  # 如果是用户页面则不需要这行

# 主题设置(如果使用GitHub自带主题)
remote_theme: "mmistakes/minimal-mistakes@4.26.2"  # 替换为你选择的主题

# 导航设置
navigation:
  - title: 首页
    url: /
  - title: 项目介绍
    url: /pages/intro
  - title: 环境配置
    url: /pages/setup
  - title: Git指南
    url: /pages/git-guide
  - title: Flutter基础
    url: /pages/flutter-basics
  - title: 贡献指南
    url: /pages/contributing

# 构建设置
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore